name: StatPlugin
version: 1.1.0
author: kelseyum
main: me.kelseyum.statplugin.Main
description: Custom Plugin for WSU Capstone


commands:
  fly: 
    description: This allows player to fly.
  hello: 
    aliases: [hi]
    description: This is the hello command!
  day:
    description: Sets time to day(1000).