name: Paddle
version: 2.0.0
author: kelsey_404
main: me.kelseyum.statplugin.Main
description: Custom Plugin for WSU Capstone
database: true


commands:
  fly: 
    description: This allows player to fly.
  hello: 
    aliases: [hi]
    description: This is the hello command!
  day:
    description: Sets time to day(1000).